### ISSUE TITLE
Create a "copy" button

### ISSUE THREAD

**Issue by ricardoruwer** [ricardoruwer/caiquenator#12]
What do you guys think about creating a button to copy the text inside the `<p data-phrase class="lead">`?

**Comment by ricardoruwer** [comment]
Tip: https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

**Comment by feliperenan** [comment]
I strong recommend https://clipboardjs.com/ 👍

**Comment by ricardoruwer** [comment]
Solved
